version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #volumes:
      #- .:/docker-rails
    ports:
      - 80:80
    depends_on:
      - app
