default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: docker-rails_development

test:
  <<: *default
  database: docker-rails_test

production:
  <<: *default
  database: docker-rails_production
